### ISSUE TITLE
Release the patches

### ISSUE THREAD

**Issue by mhalano** [rpwoodbu/libssh#1]
Hey!

I was talking with Remmina developer and he said the project uselibssh as backend. May be if you publish your patch libssh sould support Mosh and Remmina could support as well.

What you think?

**Comment by rpwoodbu** [comment]
I wonder if you're thinking I've patched libssh to add Mosh support. That's not at all what I've done. I use this patched version of libssh in the [Mosh for Chrome](https://github.com/rpwoodbu/mosh-chrome) project to initiate the Mosh session (sessions customarily are initiated via a short-lived ssh session). The patches aren't even strictly necessary for Mosh; they simply add support for ssh certs, which I needed for my own reasons. Originally I used libssh with no patches (other than to make it build with the NaCl SDK).

The original patch isn't even mine. I found it on the [libssh mailing list](http://www.libssh.org/archive/libssh/2015-03/0000000.html). It has languished there, so I simply applied it to my fork. I made a couple of minor tweaks to the patch, only to include some algorithms that weren't at top-of-mind when the original patch was submitted to the list. So if you're interested in this patch, the right thing to do is to talk it up on the libssh list.

As Remmina supports ssh, it would be neat if it added Mosh to its bag of tricks. The way to do that would be to incorporate the upstream Mosh code into Remmina similar to how I did for Mosh for Chrome. Unfortunately, that codebase isn't really setup to be used as a library; I've done some serious hackery to get around that, but that hackery is quite specific to Chrome apps. It would probably be reasonable for Remmina to spawn a mosh-client binary (perhaps one installed on the system via the normal package manager) and just pipe the stdin/stdout to Remmina's GUI.
